apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: vwnd/client
      context: client
      sync:
        manual:
          - src: src/**/*.{js,ts}
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vwnd/posts
      context: posts
      sync:
        manual:
          - src: "*.{js,ts}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vwnd/comments
      context: comments
      sync:
        manual:
          - src: "*.{js,ts}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vwnd/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.{js,ts}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vwnd/query
      context: query
      sync:
        manual:
          - src: "*.{js,ts}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: vwnd/moderation
      context: moderation
      sync:
        manual:
          - src: "*.{js,ts}"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
